services:
  db:
    image: mysql:8.0
    container_name: paintshop-db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: paintshop
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - monitoring

  app:
    image: laika23123/paintshop:${IMAGE_TAG}
    container_name: paintshop-app
    restart: unless-stopped
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/paintshop?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC&allowPublicKeyRetrieval=true&useSSL=false
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: 1234
    ports:
      - "8080:8080"
    networks:
      - monitoring

  # Prometheus
  prometheus:
    image: prom/prometheus:latest
    container_name: paintshop-prometheus
    restart: unless-stopped
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
      - '--storage.tsdb.retention.time=200h'
      - '--web.enable-lifecycle'
    networks:
      - monitoring

  # Grafana
  grafana:
    image: grafana/grafana:latest
    container_name: paintshop-grafana
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin123
      - GF_USERS_ALLOW_SIGN_UP=false
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana/provisioning:/etc/grafana/provisioning
      - ./grafana/dashboards:/var/lib/grafana/dashboards
    networks:
      - monitoring

  # MySQL Exporter (Optional)
  mysql-exporter:
    image: prom/mysqld-exporter:latest
    container_name: paintshop-mysql-exporter
    restart: unless-stopped
    ports:
      - "9104:9104"
    environment:
      - DATA_SOURCE_NAME=root:1234@(db:3306)/
    depends_on:
      - db
    networks:
      - monitoring

volumes:
  db_data:
  prometheus_data:
  grafana_data:

networks:
  monitoring:
    driver: bridge



#services:
#  db:
#    image: mysql:8.0
#    container_name: mysql-db
#    restart: always
#    environment:
#      MYSQL_ROOT_PASSWORD: root
#      MYSQL_DATABASE: paintshop
#      MYSQL_USER: root
#      MYSQL_PASSWORD: 1234
##    ports:
##      - "3307:3306"  # ⚠️ Đổi port ngoài thành 3307 để tránh xung đột
#    volumes:
#      - mysql_data:/var/lib/mysql
#
#  app:
#    build:
#      context: .
#      dockerfile: Dockerfile
#    container_name: paintshop-app
#    depends_on:
#      - mysql
#    ports:
#      - "8050:8050"
#    environment:
#      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/paintshopdb
#      SPRING_DATASOURCE_USERNAME: root
#      SPRING_DATASOURCE_PASSWORD: 1234
#    restart: on-failure
#
#volumes:
#  mysql_data:
