services:
  mysql:
    image: mysql:8.0
    container_name: mysql-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: paintshop
      MYSQL_USER: root
      MYSQL_PASSWORD: 1234
#    ports:
#      - "3307:3306"  # ⚠️ Đổi port ngoài thành 3307 để tránh xung đột
    volumes:
      - mysql_data:/var/lib/mysql

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: paintshop-app
    depends_on:
      - mysql
    ports:
      - "8050:8050"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/paintshopdb
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: 1234
    restart: on-failure

volumes:
  mysql_data:
